apiVersion: v1
kind: Namespace
metadata:
  name: front-end
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boilerplate-deployment
  namespace: front-end
  labels:
    app: boilerplate
    tier: fe
spec:
  template:
    metadata:
      name: boilerplate-pod
      namespace: front-end
      labels:
        app: boilerplate
        tier: fe
    spec:
      containers:
        - name: nginx-container
          image: manhpv151090/dockerize_expressjs:v1
          resources:
            limits:
              cpu: "1"
              memory: "2048Mi"
            requests:
              cpu: "0.25"
              memory: "256Mi"
          env:
            - name: PORT
              value: "8080"
            - name: NODE_ENV
              value: "production"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
  replicas: 2
  selector:
    matchLabels:
      app: boilerplate
      tier: fe
---
apiVersion: v1
kind: Service
metadata:
  name: boilerplate-service
  namespace: front-end
spec:
  selector:
    app: boilerplate
    tier: fe
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: boilerplate-hpa
  namespace: front-end
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: boilerplate-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
