apiVersion: v1
kind: Namespace
metadata:
  name: front-end
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boilerplate-deployment
  namespace: front-end
  labels:
    app: boilerplate
    tier: fe
spec:
  template:
    metadata:
      name: boilerplate-pod
      namespace: front-end
      labels:
        app: boilerplate
        tier: fe
    spec:
      containers:
        - name: nginx-container
          image: manhpv151090/dockerize_expressjs:latest
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          env:
            - name: PORT
              value: "8080"
            - name: NODE_ENV
              value: "production"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
  replicas: 3
  selector:
    matchLabels:
      app: boilerplate
      tier: fe
---
apiVersion: v1
kind: Service
metadata:
  name: boilerplate-service
  namespace: front-end
spec:
  selector:
    app: boilerplate
    tier: fe
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
