apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boilerplate-argocd
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: front-end
    server: "https://kubernetes.default.svc"
  source:
    path: fe
    repoURL: "https://github.com/manhpham90vn/eks_boilerplate.git"
  project: default
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
    syncOptions:
      - Timeout=180
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: argocd.manhdev.click
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
