apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boilerplate-argocd
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: front-end
    server: "https://kubernetes.default.svc"
  source:
    path: fe
    repoURL: "https://github.com/manhpham90vn/eks_boilerplate.git"
  project: default
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
    syncOptions:
      - Timeout=180